version: '3.7'
services:
  docker-angular-production:
    build: .
    container_name: docker-angular-server
    ports:
      - '8080:80'
      - '4443:443'
  docker-angular-development:
    command: >
      bash -c "npx ng serve --host 0.0.0.0 --port 4200"
    container_name: docker-angular-development-server
    build:
      context: .
      dockerfile: Dockerfile.development
      target: development
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      - .:/tmp/app/
      - ./node_modules/:/tmp/app/node_modules/
