version: '3.5'
services:
  docker-angular-service:
    container_name: docker-angular
    build: . # Location of our Dockerfile
    #volumes: # Volume binding
      #- '.:/usr/src/app'
    ports:
      - '8080:80'
      - '4443:443'
    command: >
      bash -c "yarn install && npx ng serve --host 0.0.0.0 --port 80"
